config/routes.rb
Rails.application.routes.draw do
  resources :houses
  get 'importer/form'
  post 'importer/upload'

  resources :characters do
    member do
      get :family
    end
  end

  root to: 'home#index'
end

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-dismissible alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <%= link_to image_tag("logo.png", :class=> 'logo'), root_path, :class => 'navbar-brand' %>
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>
    <div class="collapse navbar-collapse navbar-nav nav">
      <ul class="nav navbar-nav">
        <%= render 'layouts/navigation_links' %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<li><%= link_to 'Houses', houses_path %></li>
<li><%= link_to 'Characters', characters_path %></li>
<li><%= link_to 'Importer', importer_form_path %></li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Game Of Thrones" %></title>
    <link href='https://fonts.googleapis.com/css?family=Roboto:300,400,500' rel='stylesheet' type='text/css'>
    <link href="https://fonts.googleapis.com/css?family=Cormorant+Garamond:600" rel="stylesheet">
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Game Of Thrones" %>">
    <%= favicon_link_tag 'favicon.ico', id: 'favicon' %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => 'reload' %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main container">
       <%= render 'layouts/messages' %>
       <%= yield %>
    </main>
    <footer class="footer">
      <div class="container">
        <div class="col-md-12 col-lg-12">
          <p class="text-muted">Credits <a href="http://gameofthrones.wikia.com/wiki/Game_of_Thrones_Wiki">Wikia Games of Thrones</a> under the Creative Commons Attribution-Share Alike License Unported (CC BY-SA 3.0)</p>
        </div>
      </div>
    </footer>
  </body>
</html>